apiVersion: v1
kind: Service
metadata:
    name: backend
    namespace: backend
spec:
    selector:
            app: backend    
    type: ClusterIP
    ports:
        - port: 8000
          targetPort: 8000
          protocol: TCP
    