FROM nginx:stable-alpine

# Copy your static files into nginx's default serving directory
COPY ./static/ /usr/share/nginx/html/static

# Expose port 80
EXPOSE 80

# Default nginx command runs automatically
