apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: database
spec:
  selector:
    app: database
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP